
    create table client (
       id bigint generated by default as identity,
        password varchar(255),
        username varchar(255),
        wallet double not null,
        primary key (id)
    );

    create table order (
       id bigint generated by default as identity,
        order_time timestamp,
        user_id bigint,
        primary key (id)
    );

    create table order_product (
       order_id bigint not null,
        product_id bigint not null
    );

    create table product (
       id bigint generated by default as identity,
        date timestamp,
        description varchar(255),
        image varchar(255),
        price double not null,
        stocks integer not null,
        title varchar(255),
        user_id bigint,
        primary key (id)
    );

    alter table client 
       add constraint username_unique unique (username);

    alter table order 
       add constraint FKjhh5gpob889qok2kvwjyj4i3p 
       foreign key (user_id) 
       references client;

    alter table order_product 
       add constraint FKhnfgqyjx3i80qoymrssls3kno 
       foreign key (product_id) 
       references product;

    alter table product 
       add constraint FK3p162nkqbgm8xg94koy8it3j9 
       foreign key (user_id) 
       references client;
