
    create table client (
       id bigint generated by default as identity,
        password varchar(255),
        username varchar(255),
        wallet double not null,
        primary key (id)
    );

    create table orders (
       id bigint generated by default as identity,
        order_time timestamp,
        quantity integer not null,
        client_id bigint,
        products_id bigint,
        primary key (id)
    );

    create table product (
       id bigint generated by default as identity,
        date timestamp,
        description varchar(255),
        image varchar(255),
        price double not null,
        stocks integer not null,
        title varchar(255),
        client_id bigint,
        primary key (id)
    );

    alter table client 
       add constraint username_unique unique (username);

    alter table orders 
       add constraint FK17yo6gry2nuwg2erwhbaxqbs9 
       foreign key (client_id) 
       references client;

    alter table orders 
       add constraint FK1gb3bxe4u93n4cd7ptoq3e3ax 
       foreign key (products_id) 
       references product;

    alter table product 
       add constraint FK3g8nmhhbt7mwbf9r0g5qon8m0 
       foreign key (client_id) 
       references client;
